In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import socketclient
import numpy as np

In [3]:
s = socketclient.SocketClient()

In [4]:
s.connect()

Starting Client
Create a TCP/IP socket
Connect the socket to the server port
Connecting to: ('desktop', 20801)
Connected to server


## ECHO

In [5]:
s.echo(message="Hello there!")

Sending: ECHO


Sending: Hello there!


Received from server: Hello there!




## STATUS

In [6]:
s.status()

getting status
Sending: STATUS


Received from server: NEEDINIT


## INIT

In [7]:
s.init(bead_index=5, init_str='')

initializing
Sending: INIT


Sending: 5


Sending: 0




In [8]:
s.init(bead_index=5, init_str='init my calc')

initializing
Sending: INIT


Sending: 5


Sending: 12


Sending: init my calc




## POSDATA

In [9]:
cell_vec_mat = np.array([0.123, 3453, 5436.4, 2342.4434535, 657575.7, 3, 3453/7, 345, 0], dtype=float)
cell_vec_mat

array([1.23000000e-01, 3.45300000e+03, 5.43640000e+03, 2.34244345e+03,
       6.57575700e+05, 3.00000000e+00, 4.93285714e+02, 3.45000000e+02,
       0.00000000e+00])

In [10]:
inv_mat = np.array([0.123, 3453, 5436.4, 2342.4434535, 657575.7, 3, 3453/7, 345, 0], dtype=float)
inv_mat

array([1.23000000e-01, 3.45300000e+03, 5.43640000e+03, 2.34244345e+03,
       6.57575700e+05, 3.00000000e+00, 4.93285714e+02, 3.45000000e+02,
       0.00000000e+00])

In [11]:
num_atoms = 11
atom_positions = (np.random.random_sample((num_atoms, 3)) - 0.5) * 10
atom_positions

array([[-2.16063927,  2.4184463 ,  3.87831218],
       [ 2.93246657, -0.92166179,  3.16526586],
       [-4.03678624,  4.08162376, -0.89057306],
       [ 3.29836275,  2.36671751, -0.57729478],
       [-4.87803126,  1.93064507, -2.80085129],
       [ 0.16048747,  4.52909809, -4.15599484],
       [-0.24949477, -4.07567694, -1.8787151 ],
       [ 2.92506877, -1.73053577,  1.68671259],
       [ 1.0601537 ,  1.14862208, -0.3543041 ],
       [-0.51657715,  4.98241904,  2.25599851],
       [ 2.24916415, -0.22015417, -4.15157621]])

In [17]:
s.posdata(cell_vec_mat, inv_mat, num_atoms, atom_positions)

sending position data
Sending: POSDATA


There was an issue sending
000000.123
00003453.0
00005436.4
2342.4434535
00657575.7
00000003.0
493.2857142857143
00000345.0
00000000.0


## GETFORCE

## ABORT

In [ ]:
s.abort()