In [10]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [11]:
import socketclient
import numpy as np

In [12]:
s = socketclient.SocketClient()

In [13]:
s.connect()

Starting Client
Create a TCP/IP socket
Connect the socket to the server port
Connecting to: ('desktop', 20801)
Connected to server


## ECHO

In [14]:
s.echo(message="Hello there!")

Sending: ECHO


Sending: Hello there!


Received from server: Hello there!




## STATUS

In [15]:
s.status()

getting status
Sending: STATUS


Received from server: NEEDINIT


## INIT

In [16]:
s.init(bead_index=5, init_str='')

initializing
Sending: INIT




In [17]:
s.init(bead_index=5, init_str='1')

initializing
Sending: INIT


Sending: 1




In [18]:
s.init(bead_index=5, init_str='init my calc')

initializing
Sending: INIT


Sending: init my calc




## POSDATA

In [19]:
s.status()

getting status
Sending: STATUS


Received from server: READY


In [20]:
cell_vec_mat = np.array([0.123, 3453, 5436.4, 2342.4434535, 657575.7, 3, 3453/7, 345, 0], dtype=float)
cell_vec_mat

array([1.23000000e-01, 3.45300000e+03, 5.43640000e+03, 2.34244345e+03,
       6.57575700e+05, 3.00000000e+00, 4.93285714e+02, 3.45000000e+02,
       0.00000000e+00])

In [21]:
inv_mat = np.array([0.123, 3453, 5436.4, 2342.4434535, 657575.7, 3, 3453/7, 345, 0], dtype=float) * 2
inv_mat

array([2.46000000e-01, 6.90600000e+03, 1.08728000e+04, 4.68488691e+03,
       1.31515140e+06, 6.00000000e+00, 9.86571429e+02, 6.90000000e+02,
       0.00000000e+00])

In [22]:
num_atoms = 11
atom_positions = (np.random.random_sample((num_atoms, 3)) - 0.5) * 10
atom_positions

array([[-3.50981983, -0.29726233,  2.80727578],
       [ 4.35917067, -0.03856853,  4.68240844],
       [-4.47244653,  1.40841559,  0.96124878],
       [ 3.02822936, -0.19636269, -4.92133997],
       [-3.7007506 , -3.1392143 ,  1.8244014 ],
       [ 3.3456952 ,  4.47375402,  3.47303038],
       [-3.202245  ,  2.42089667,  4.31555497],
       [-2.74950618, -0.21738696,  0.48733519],
       [ 3.71334927,  2.25908487,  0.07480906],
       [-3.26304023, -3.25139511, -2.98835234],
       [ 4.07013193,  0.84825969, -1.60265214]])

In [23]:
s.posdata(cell_vec_mat, inv_mat, num_atoms, atom_positions)

sending position data
Sending: POSDATA


0.123
3453.0
5436.4
2342.4434535
657575.7
3.0
493.2857142857143
345.0
0.0


0.246
6906.0
10872.8
4684.886907
1315151.4
6.0
986.5714285714286
690.0
0.0


b'\x0b\x00\x00\x00' ---> 11 

-3.509819832757514
-0.29726233228245746
2.807275781837699
4.3591706721548205
-0.03856852742339156
4.682408444877443
-4.472446532898495
1.4084155854317537
0.961248777686099
3.0282293551257364
-0.19636269381644422
-4.921339967063742
-3.700750596926059
-3.1392142984650007
1.8244013957793126
3.3456952045752217
4.473754023392421
3.4730303812357457
-3.2022450035422203
2.4208966689367886
4.315554967083866
-2.7495061829488545
-0.2173869559500763
0.487335194495927
3.7133492698081705
2.2590848727701642
0.07480905912137237
-3.2630402341150058
-3.2513951068761724
-2.988352338072099
4.070131925707808
0.848259691870813
-1.602652138574323


## GETFORCE

## ABORT

In [24]:
s.abort()

Instructing server to shut down.
Sending: ABORT


Closing socket.
