In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import socketclient
import numpy as np

In [3]:
s = socketclient.SocketClient()

In [4]:
s.connect()

Starting Client
Create a TCP/IP socket
Connect the socket to the server port
Connecting to: ('desktop', 20801)
Connected to server


## ECHO

In [5]:
s.echo(message="Hello there!")

Sending: ECHO


Sending: Hello there!


Received from server: Hello there!




## STATUS

In [6]:
s.status()

getting status
Sending: STATUS


Received from server: NEEDINIT


## INIT

In [7]:
s.init(bead_index=5, init_str='')

initializing
Sending: INIT


Sending: 5


Sending: 0




In [8]:
s.init(bead_index=5, init_str='init my calc')

initializing
Sending: INIT


Sending: 5


Sending: 12


Sending: init my calc




## POSDATA

In [9]:
s.status()

getting status
Sending: STATUS


Received from server: READY


In [10]:
cell_vec_mat = np.array([0.123, 3453, 5436.4, 2342.4434535, 657575.7, 3, 3453/7, 345, 0], dtype=float)
cell_vec_mat

array([1.23000000e-01, 3.45300000e+03, 5.43640000e+03, 2.34244345e+03,
       6.57575700e+05, 3.00000000e+00, 4.93285714e+02, 3.45000000e+02,
       0.00000000e+00])

In [11]:
inv_mat = np.array([0.123, 3453, 5436.4, 2342.4434535, 657575.7, 3, 3453/7, 345, 0], dtype=float) * 2
inv_mat

array([1.23000000e-01, 3.45300000e+03, 5.43640000e+03, 2.34244345e+03,
       6.57575700e+05, 3.00000000e+00, 4.93285714e+02, 3.45000000e+02,
       0.00000000e+00])

In [12]:
num_atoms = 11
atom_positions = (np.random.random_sample((num_atoms, 3)) - 0.5) * 10
atom_positions

array([[-2.45113324,  3.40619686, -0.88455925],
       [-3.63950185,  0.66149921,  4.27591567],
       [-0.61527868,  2.85490864,  1.88931536],
       [-0.28249894,  2.91274311, -4.38099839],
       [ 1.36827037,  3.81295918, -2.20515249],
       [-3.98343132,  3.78799932,  2.83727073],
       [ 2.95524321,  3.64857692,  4.34697697],
       [ 2.95411115, -1.19609548, -4.12879759],
       [-0.66300957,  2.97786202, -0.10945545],
       [-1.44460394, -4.30497091, -3.7980594 ],
       [ 4.62367955, -0.62700828,  4.27922876]])

In [13]:
s.posdata(cell_vec_mat, inv_mat, num_atoms, atom_positions)

sending position data
Sending: POSDATA


0.123
3453.0
5436.4
2342.4434535
657575.7
3.0
493.2857142857143
345.0
0.0
0.123
3453.0
5436.4
2342.4434535
657575.7
3.0
493.2857142857143
345.0
0.0


## GETFORCE

## ABORT

In [ ]:
s.abort()