In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import socketclient
import numpy as np

In [3]:
s = socketclient.SocketClient()

In [4]:
s.connect()

Starting Client
Create a TCP/IP socket
Connect the socket to the server port
Connecting to: ('desktop', 20801)
Connected to server


## ECHO

In [5]:
s.echo(message="Hello there!")

Sending: ECHO


Sending: Hello there!


Received from server: Hello there!




## STATUS

In [6]:
s.status()

getting status
Sending: STATUS


Received from server: NEEDINIT


## INIT

In [7]:
s.init(bead_index=5, init_str='')

initializing
Sending: INIT


Sending: 5


Sending: 0




In [8]:
s.init(bead_index=5, init_str='init my calc')

initializing
Sending: INIT


Sending: 5


Sending: 12


Sending: init my calc




## POSDATA

In [9]:
s.status()

getting status
Sending: STATUS


Received from server: READY


In [10]:
cell_vec_mat = np.array([0.123, 3453, 5436.4, 2342.4434535, 657575.7, 3, 3453/7, 345, 0], dtype=float)
cell_vec_mat

array([1.23000000e-01, 3.45300000e+03, 5.43640000e+03, 2.34244345e+03,
       6.57575700e+05, 3.00000000e+00, 4.93285714e+02, 3.45000000e+02,
       0.00000000e+00])

In [11]:
inv_mat = np.array([0.123, 3453, 5436.4, 2342.4434535, 657575.7, 3, 3453/7, 345, 0], dtype=float) * 2
inv_mat

array([2.46000000e-01, 6.90600000e+03, 1.08728000e+04, 4.68488691e+03,
       1.31515140e+06, 6.00000000e+00, 9.86571429e+02, 6.90000000e+02,
       0.00000000e+00])

In [12]:
num_atoms = 11
atom_positions = (np.random.random_sample((num_atoms, 3)) - 0.5) * 10
atom_positions

array([[ 0.51273366, -1.17407878,  3.29928083],
       [ 4.13762727,  0.27149415,  2.11605898],
       [-2.11512987,  1.35378568, -2.60813114],
       [ 4.09937759, -1.76618109, -2.45893102],
       [ 3.40442689,  3.03099917, -3.94832317],
       [-2.23190758, -0.32448177,  3.72489944],
       [ 1.39058536,  0.16455313, -2.99064501],
       [ 3.67934519,  1.57947169, -2.81382412],
       [ 2.11292231, -2.45966631, -2.17235815],
       [-0.84067908, -0.99631573, -1.45306598],
       [-2.13655079,  3.31927584, -1.50164327]])

In [13]:
s.posdata(cell_vec_mat, inv_mat, num_atoms, atom_positions)

sending position data
Sending: POSDATA


0.123
3453.0
5436.4
2342.4434535
657575.7
3.0
493.2857142857143
345.0
0.0


0.246
6906.0
10872.8
4684.886907
1315151.4
6.0
986.5714285714286
690.0
0.0


b'\x0b\x00\x00\x00' ---> 11 

0.5127336621232004
-1.1740787793903584
3.2992808268101728
4.137627274065251
0.27149414602247623
2.1160589805108367
-2.1151298733271116
1.3537856792227243
-2.6081311364114326
4.099377590635282
-1.7661810873244133
-2.4589310193312897
3.404426891071899
3.0309991687124063
-3.9483231690950396
-2.231907582059457
-0.32448177060940164
3.7248994445925088
1.3905853590371786
0.16455312880930606
-2.9906450095244983
3.679345191283608
1.5794716935023667
-2.8138241174610323
2.112922311162977
-2.4596663132239325
-2.1723581530245593
-0.8406790797952246
-0.9963157304732329
-1.453065975213852
-2.1365507898687985
3.3192758351185825
-1.5016432728797757


## GETFORCE

## ABORT

In [14]:
s.abort()

Instructing server to shut down.
Sending: ABORT


Closing socket.
